name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Uninstall old trmnl_preview gem
        run: gem uninstall trmnl_preview -aIx || true

      - name: Install trmnl_preview 0.5.4
        run: gem install trmnl_preview -v 0.5.4 --force

      - name: Install xdg 6.6.0
        run: gem install xdg -v 6.6.0

      - name: Run trmnlp build
        run: trmnlp build